package com.yet.pets.compose

import android.util.Base64

/**
 * On-device verification fixtures for the Phase 3 Android execution gate.
 *
 * Every image below was generated on the host with an independent reference
 * encoder (Pillow) and verified there before embedding:
 *
 * - PNG/JPEG/GIF via Pillow; WebP via Pillow/libwebp.
 * - `webpLossy` carries a `VP8 ` chunk (lossy), `webpLossless` a `VP8L`
 *   chunk, `webpAlpha` a `VP8X` chunk (alpha), `webpAnimated` a `VP8X`
 *   chunk plus an `ANIM` chunk (2 frames: red -> blue).
 * - `gifAnimated` is 2 frames: red -> blue.
 *
 * Pillow re-open confirmed dimensions and first-frame pixels on the host, so
 * a matching on-device decode proves the Android platform codec path, not
 * the fixture.
 */
internal const val FIX_PNG_VALID_B64 = "iVBORw0KGgoAAAANSUhEUgAAAAwAAAAKCAIAAAAPTiitAAAAFklEQVR4nGM8oWHDQAgwEVQxqohoRQC/wQFASnD1sAAAAABJRU5ErkJggg==" // 12x10 solid (200,40,60), 79 bytes

internal const val FIX_PNG_DENSITY_B64 = "iVBORw0KGgoAAAANSUhEUgAAAMAAAADQCAIAAADeaPnLAAACEUlEQVR4nO3SsQ3AIADAMGDsxZzIWf2hGVAl+4IMmc/ZA75atwP4NwORGIjEQCQGIjEQiYFIDERiIBIDkRiIxEAkBiIxEImBSAxEYiASA5EYiMRAJAYiMRCJgUgMRGIgEgORGIjEQCQGIjEQiYFIDERiIBIDkRiIxEAkBiIxEImBSAxEYiASA5EYiMRAJAYiMRCJgUgMRGIgEgORGIjEQCQGIjEQiYFIDERiIBIDkRiIxEAkBiIxEImBSAxEYiASA5EYiMRAJAYiMRCJgUgMRGIgEgORGIjEQCQGIjEQiYFIDERiIBIDkRiIxEAkBiIxEImBSAxEYiASA5EYiMRAJAYiMRCJgUgMRGIgEgORGIjEQCQGIjEQiYFIDERiIBIDkRiIxEAkBiIxEImBSAxEYiASA5EYiMRAJAYiMRCJgUgMRGIgEgORGIjEQCQGIjEQiYFIDERiIBIDkRiIxEAkBiIxEImBSAxEYiASA5EYiMRAJAYiMRCJgUgMRGIgEgORGIjEQCQGIjEQiYFIDERiIBIDkRiIxEAkBiIxEImBSAxEYiASA5EYiMRAJAYiMRCJgUgMRGIgEgORGIjEQCQGIjEQiYFIDERiIBIDkRiIxEAkBiIxEImBSAxEYiASA5EYiMRAJAYiMRCJgUgMRGIgEgORGIjEQCQGIjEQiYFIDERiIBIDkRiIxEAkBiIxEImBSF5IwwLqqqwwLQAAAABJRU5ErkJggg==" // 192x208 solid (10,200,120), 586 bytes

internal const val FIX_JPEG_VALID_B64 = "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD/wAARCAAMABADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDxqiiivkj+0D//2Q==" // 16x12 quality-92 solid (200,40,60), 634 bytes

internal const val FIX_GIF_STATIC_B64 = "R0lGODdhDgALAIEAAP8AAAAAAAAAAAAAACwAAAAADgALAAAIFwABCBxIsKDBgwgTKlzIsKHDhxAjAggIADs=" // 14x11 single red frame, 62 bytes

internal const val FIX_GIF_ANIMATED_B64 = "R0lGODlhDgALAIEAAP8AAAAAAAAAAAAAACH/C05FVFNDQVBFMi4wAwEAAAAh+QQAFAAAACwAAAAADgALAAAIFwABCBxIsKDBgwgTKlzIsKHDhxAjAggIACH5BAEUAAEALAAAAAAOAAsAgQAA/wAAAAAAAAAAAAgXAAEIHEiwoMGDCBMqXMiwocOHECMCCAgAOw==" // 14x11 red->blue, 145 bytes

internal const val FIX_WEBP_LOSSY_B64 = "UklGRjwAAABXRUJQVlA4IDAAAADQAQCdASoQAAwAAMASJaACdLoB+AADsAD+9uYH/izkYjs83/7PL+zy/s8v/s2AAAA=" // 16x12 VP8 chunk, 68 bytes

internal const val FIX_WEBP_LOSSLESS_B64 = "UklGRh4AAABXRUJQVlA4TBEAAAAvD8ACAAdQlCKXp/+BiOh/AAA=" // 16x12 VP8L chunk, 38 bytes

internal const val FIX_WEBP_ALPHA_B64 = "UklGRmgAAABXRUJQVlA4WAoAAAAQAAAADwAACwAAQUxQSA8AAAABDzD/ERHiVaoR/Y+ZmRkAVlA4IDIAAAAQAgCdASoQAAwAAMASJaACdLoB+AH6AAPIAP7wUx//mudBpyX/Ndv/2MmoOAZf9iPAAA==" // 16x12 VP8X chunk w/ alpha checker, 112 bytes

internal const val FIX_WEBP_ANIMATED_B64 = "UklGRsQAAABXRUJQVlA4WAoAAAACAAAADwAACwAAQU5JTQYAAAAAAAAAAABBTk1GSgAAAAAAAAAAAA8AAAsAAMgAAAJWUDggMgAAADABAJ0BKhAADAABQCYloAADcAD+8ut///mwP/bz/wR6Af//0uD//pcH//S4P/SkAAAAQU5NRkYAAAAAAAAAAAAPAAALAADIAAAAVlA4IC4AAAA0AQCdASoQAAwAAAAmJaAAA3AA/vtV4///S4P/+lwf/9Lg/9Lg//rV5Vesq6AA" // 16x12 VP8X+ANIM red->blue, 204 bytes

internal fun decodeFixture(b64: String): ByteArray = Base64.decode(b64, Base64.DEFAULT)
